// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeZUlvwYIKfkKg8mEX3as18eohutBuD2c',
    appId: '1:316463308931:web:65628c8118f4f7021e7bb6',
    messagingSenderId: '316463308931',
    projectId: 'forkcast-89100',
    authDomain: 'forkcast-89100.firebaseapp.com',
    storageBucket: 'forkcast-89100.firebasestorage.app',
    measurementId: 'G-W7XJ5SN1CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeQ1eEFC903pD10IWZRrQLZ8Jn6xyLiOo',
    appId: '1:316463308931:android:ba16c26ecbdd28391e7bb6',
    messagingSenderId: '316463308931',
    projectId: 'forkcast-89100',
    storageBucket: 'forkcast-89100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw8SoxhawOgrngkWnhZ_JC6IU2sy2_GCE',
    appId: '1:316463308931:ios:73732a69ba74d9bd1e7bb6',
    messagingSenderId: '316463308931',
    projectId: 'forkcast-89100',
    storageBucket: 'forkcast-89100.firebasestorage.app',
    iosBundleId: 'com.example.forkcast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw8SoxhawOgrngkWnhZ_JC6IU2sy2_GCE',
    appId: '1:316463308931:ios:73732a69ba74d9bd1e7bb6',
    messagingSenderId: '316463308931',
    projectId: 'forkcast-89100',
    storageBucket: 'forkcast-89100.firebasestorage.app',
    iosBundleId: 'com.example.forkcast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeZUlvwYIKfkKg8mEX3as18eohutBuD2c',
    appId: '1:316463308931:web:d23e99c5b04f079b1e7bb6',
    messagingSenderId: '316463308931',
    projectId: 'forkcast-89100',
    authDomain: 'forkcast-89100.firebaseapp.com',
    storageBucket: 'forkcast-89100.firebasestorage.app',
    measurementId: 'G-FPVHQ82DN6',
  );
}
